package constants;



public interface Const
{
	int POINTS_FOR_SCROLL_CREATING = 5;
	int POINTS_FOR_BEST_SOLUTION = 1;
	int SCROLL_CREATION_TIMEOUT = 24;
	int TOPICS_PAGE_SIZE = 15;
	int SCROLLS_PAGE_SIZE = 9;
	int EXEC_TIMEOUT = 3000;
	int BEST_SOLUTION_TIME_DIFF = 5;
}
