package constants;



public interface Const
{
	int POINTS_FOR_SCROLL_CREATING = 5;
	int POINTS_FOR_DELETING_SCROLL = POINTS_FOR_SCROLL_CREATING;
	int POINTS_FOR_SOLVING_SCROLL = 1;
	int POINTS_LOSS_FOR_BAD_SCROLL = POINTS_FOR_SCROLL_CREATING * 2;
	int SCROLL_CREATION_TIMEOUT = 24;
	int TOPICS_PAGE_SIZE = 15;
	int SCROLLS_PAGE_SIZE = 9;
	int EXEC_TIMEOUT = 10000;
	int BEST_SOLUTION_TIME_DIFF = 5;
}
