package constants;



public enum CStatus
{
  OK,
  INVALID_REQUEST,
  EMPTY_DATA,
  INVALID_NICKNAME,
  INVALID_EMAIL,
  INVALID_LOGIN,
  INVALID_PASSWORD,
  INVALID_SIDE,
  INVALID_FIELD_TYPE,
	INVALID_IMAGE,
  USER_ALREADY_EXIST,
  USER_NOT_CONFIRMED,
  NICKNAME_ALREADY_IN_USE,
  INVALID_TOKEN,
  WRONG_LOGIN_OR_PASSWORD,
	USER_DOES_NOT_EXIST,
	ACCESS_DENIED,
	ACCOUNT_REMOVED	
}
