package constants;



public enum CStatus
{
  OK,
  INVALID_REQUEST,
  EMPTY_IMAGE_DATA,
  INVALID_NICKNAME,
  INVALID_EMAIL,
  INVALID_LOGIN,
  INVALID_PASSWORD,
  INVALID_SIDE,
  INVALID_FIELD_TYPE,
	INVALID_IMAGE,
	INVALID_TITLE,
	INVALID_ID,
	INVALID_TOPICS,
  USER_ALREADY_EXIST,
  USER_NOT_CONFIRMED,
  NICKNAME_ALREADY_IN_USE,
  INVALID_TOKEN,
  WRONG_LOGIN_OR_PASSWORD,
	USER_DOES_NOT_EXIST,
	ACCESS_DENIED,
	ACCOUNT_REMOVED,
	SCROLL_DOES_NOT_EXIST,
	SCROLL_CREATION_LIMIT,
	SCROLL_HAS_NOT_BEEN_VISITED,
	SCROLL_HAS_NO_SOLUTION,
	TOPIC_DOES_NOT_EXIST,
	TOPIC_DOES_NOT_CONTAIN_SCROLLS,
	USER_HAS_NO_SCROLLS,
	NO_SCROLLS_ON_YOUR_SIDE,
	TOKEN_EXPIRED	
}
