package constants;



public enum Status
{
  OK,
  INVALID_REQUEST,
  EMPTY_DATA,
  INVALID_NICKNAME,
  INVALID_EMAIL,
  INVALID_LOGIN,
  INVALID_PASSWORD,
  INVALID_SIDE,
  INVALID_FIELD_TYPE,
  USER_ALREADY_EXIST,
  USER_NOT_CONFIRMED,
  NICKNAME_ALREADY_IN_USE,
  INVALID_TOKEN,
  WRONG_LOGIN_OR_PASSWORD,

  ///////////////////

  INVALID_ID,
  NO_TASKS,
  TASK_DOES_NOT_EXIST,
  NO_SOLUTION,
  PERMISSIONS_DENIED
}
